export const DI_TOKENS = {
  CONCERT_REPOSITORY: 'CONCERT_REPOSITORY',
  RESERVATION_REPOSITORY: 'RESERVATION_REPOSITORY',
  PAYMENT_REPOSITORY: 'PAYMENT_REPOSITORY',
  QUEUE_REPOSITORY: 'QUEUE_REPOSITORY',
  POINT_REPOSITORY: 'POINT_REPOSITORY',
} as const;
